language: elixir
elixir:
  - 1.2.2
otp_release:
  - 18.2.1
addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database fyler_test;' -U postgres
  - cp config/test.travis.exs config/test.exs
